---
- name: debug to print group of variables
  hosts: localhost
  connection: local
  vars: 
    var1: default1
    var2: default2
    var3: default3
    var4: default4
  tasks:
    - name: debugvars
      vars: 
        var_list: 
          - "{{var1}}"
          - "{{var2}}"
          - "{{var3}}"
          - "{{var4}}"
      ansible.builtin.debug:
        var: var_list

    - name: "Artifact URL of test results to Workflows"
      set_stats:
        data:
          artifact_var1: "{{var1}}"
          artifact_var2: "{{var2}}"
          artifact_var3: "{{var3}}"
          artifact_var4: "{{var4}}"